name: Build pull request

on:
  pull_request:
    types: ['opened', 'synchronize']
    branches: [ 'main' ]

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
            artifact-name: elevo-messenger-macos-aarch64
            artifact-path: src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
            artifact-name: elevo-messenger-macos-x86_64
            artifact-path: src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.dmg
          - platform: 'windows-latest'
            args: ''
            artifact-name: elevo-messenger-windows-x86_64
            artifact-path: src-tauri/target/release/bundle/msi/*.msi

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
        with: 
          submodules: true

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            cinny/package-lock.json

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up non-macOS builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install submodule dependencies
        run: cd cinny && npm ci

      - name: install frontend dependencies
        run: npm ci

      - uses: tauri-apps/tauri-action@v0.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: "--max_old_space_size=4096"
          APPLE_SIGNING_IDENTITY: "-"
        with:
          args: ${{ matrix.args }} --config '{"bundle":{"createUpdaterArtifacts":false}}'

      - name: upload app artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}
          if-no-files-found: error
